apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: notification-demo
  namespace: argocd
  annotations:
    entityguid: "<NEW RELIC ENTITY GUID>"
    # notifications.argoproj.io/subscribe.newrelic-app-sync-succeeded.newrelic: ""
    notifications.argoproj.io/subscribe.newrelic-app-deployed.newrelic: ""

spec:
  destination:
    name: ''
    namespace: notification-demo
    server: 'https://kubernetes.default.svc'
  source:
    path: demo-app
    repoURL: 'https://github.com/bpschmitt/newrelic-argocd-notification-example'
    targetRevision: main
  sources: []
  project: demos
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
